import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import fixture from "../src/__tests__/fixtures/command-conformance.json";
import historicalArtifact from "../src/__tests__/fixtures/conformance-0.0.42.json";
import {
	COMMAND_TRANSITIONS,
	commandFailureCodeSchema,
	NORMALIZED_FAILURE_CATALOG,
	WORKFLOW_TRANSITIONS,
} from "../src/command";
import { canonicalJson } from "../src/serialize";

export function buildConformanceArtifact(packageVersion: string) {
	if (!/^\d+\.\d+\.\d+$/.test(packageVersion)) {
		throw new Error(
			"Contracts package version must be a stable semantic version.",
		);
	}
	const [major, minor] = packageVersion.split(".").map(Number);
	const [historicalMajor, historicalMinor] = historicalArtifact.version
		.split(".")
		.map(Number);
	if (
		major !== historicalMajor ||
		minor < historicalMinor ||
		minor > historicalMinor + 1
	) {
		throw new Error(
			`Preserve the previous minor conformance artifact before generating ${packageVersion}.`,
		);
	}

	const previousMinorFixtureSuite =
		minor === historicalMinor
			? historicalArtifact.previousMinorFixtureSuite
			: {
					artifactVersion: historicalArtifact.version,
					note: `Fixture suite from the ${historicalArtifact.version} conformance artifact.`,
					...historicalArtifact.currentFixtureSuite,
				};
	const acceptedPairs = [
		{ consumer: packageVersion, artifact: packageVersion },
	];
	if (previousMinorFixtureSuite.artifactVersion !== packageVersion) {
		acceptedPairs.push({
			consumer: packageVersion,
			artifact: previousMinorFixtureSuite.artifactVersion,
		});
	}
	const compatibilityMatrix = {
		semverPolicy: historicalArtifact.compatibilityMatrix.semverPolicy,
		acceptedPairs,
		rejectedPairs: [
			{
				consumer: packageVersion,
				artifact: `${major + 1}.0.0`,
				reason: "major_break",
			},
			{
				consumer: `${major}.${minor + 1}.0`,
				artifact: packageVersion,
				reason: "unlisted_pair",
			},
		],
	};
	const payloadWithoutDigest = {
		packageVersion,
		artifactVersion: packageVersion,
		failureCodes: [...commandFailureCodeSchema.options],
		normalizedFailures: NORMALIZED_FAILURE_CATALOG,
		commandTransitions: COMMAND_TRANSITIONS,
		workflowTransitions: WORKFLOW_TRANSITIONS,
		compatibilityMatrix,
		currentFixtureSuite: fixture,
		previousMinorFixtureSuite,
	};
	const payloadJson = JSON.parse(
		JSON.stringify(payloadWithoutDigest),
	) as import("../src/json-value").JsonValue;
	const digest = createHash("sha256")
		.update(canonicalJson(payloadJson))
		.digest("hex");

	return {
		version: packageVersion,
		digest,
		compatibilityMatrix,
		currentFixtureSuite: fixture,
		previousMinorFixtureSuite,
	};
}

function generateConformance(): void {
	const root = dirname(fileURLToPath(import.meta.url));
	const packageJson: unknown = JSON.parse(
		readFileSync(join(root, "../package.json"), "utf8"),
	);
	if (
		typeof packageJson !== "object" ||
		packageJson === null ||
		!("version" in packageJson) ||
		typeof packageJson.version !== "string"
	) {
		throw new Error("Contracts package.json must contain a version string.");
	}
	const artifact = buildConformanceArtifact(packageJson.version);
	const second = buildConformanceArtifact(packageJson.version);
	if (JSON.stringify(second) !== JSON.stringify(artifact)) {
		throw new Error(
			"Conformance artifact is unstable across repeated generation.",
		);
	}

	const jsonPath = join(root, "../src/generated/conformance-artifact.json");
	const tsPath = join(root, "../src/generated/conformance-artifact.ts");
	writeFileSync(jsonPath, `${JSON.stringify(artifact, null, "\t")}\n`, "utf8");
	writeFileSync(
		tsPath,
		`/* Generated by scripts/generate-conformance.ts — do not edit by hand. */\nexport const conformanceArtifact = ${JSON.stringify(artifact, null, "\t")} as const;\n`,
		"utf8",
	);
	process.stdout.write(
		`Wrote ${jsonPath}\nWrote ${tsPath}\nCONFORMANCE_DIGEST=${artifact.digest}\n`,
	);
}

if (
	process.argv[1] &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
	generateConformance();
}
