import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import fixture from "../src/__tests__/fixtures/command-conformance.json";
import {
	COMMAND_TRANSITIONS,
	commandFailureCodeSchema,
	NORMALIZED_FAILURE_CATALOG,
	WORKFLOW_TRANSITIONS,
} from "../src/command";
import { canonicalJson } from "../src/serialize";

const packageVersion = "0.0.42";
const artifactVersion = "0.0.42";

const compatibilityMatrix = {
	semverPolicy: {
		major: "May break schemas or meaning.",
		minor:
			"May add Command versions, optional fields, or fixtures without changing existing normalized behavior.",
		patch:
			"May repair implementation or documentation without changing an existing wire schema.",
	},
	acceptedPairs: [
		{ consumer: "0.0.42", artifact: "0.0.42" },
		{ consumer: "0.0.42", artifact: "0.0.0" },
	],
	rejectedPairs: [
		{ consumer: "0.0.42", artifact: "1.0.0", reason: "major_break" },
		{ consumer: "0.1.0", artifact: "0.0.42", reason: "unlisted_pair" },
	],
};

const currentFixtureSuite = fixture;
const previousMinorFixtureSuite = {
	artifactVersion: "0.0.0",
	note: "Bootstrap previous-minor suite; identical to 0.0.42 envelope and transitions.",
	validRequest: fixture.validRequest,
	commandTransitions: fixture.commandTransitions,
	workflowTransitions: fixture.workflowTransitions,
};

const payloadWithoutDigest = {
	packageVersion,
	artifactVersion,
	failureCodes: [...commandFailureCodeSchema.options],
	normalizedFailures: NORMALIZED_FAILURE_CATALOG,
	commandTransitions: COMMAND_TRANSITIONS,
	workflowTransitions: WORKFLOW_TRANSITIONS,
	compatibilityMatrix,
	currentFixtureSuite,
	previousMinorFixtureSuite,
};

const payloadJson = JSON.parse(
	JSON.stringify(payloadWithoutDigest),
) as import("../src/json-value").JsonValue;

const digest = createHash("sha256")
	.update(canonicalJson(payloadJson))
	.digest("hex");

const artifact = {
	version: artifactVersion,
	digest,
	compatibilityMatrix,
	currentFixtureSuite,
	previousMinorFixtureSuite,
};

const root = dirname(fileURLToPath(import.meta.url));
const jsonPath = join(root, "../src/generated/conformance-artifact.json");
const tsPath = join(root, "../src/generated/conformance-artifact.ts");
writeFileSync(jsonPath, `${JSON.stringify(artifact, null, "\t")}\n`, "utf8");
writeFileSync(
	tsPath,
	`/* Generated by scripts/generate-conformance.ts — do not edit by hand. */\nexport const conformanceArtifact = ${JSON.stringify(artifact, null, "\t")} as const;\n`,
	"utf8",
);

const second = createHash("sha256")
	.update(canonicalJson(payloadJson))
	.digest("hex");
if (second !== digest) {
	throw new Error("Conformance digest is unstable across repeated generation.");
}

process.stdout.write(
	`Wrote ${jsonPath}\nWrote ${tsPath}\nCONFORMANCE_DIGEST=${digest}\n`,
);
