/**
 * Store Runtime database schema.
 *
 * Drizzle owns the schema from here; `packages/db` is its only owner.
 * Framework tables live in `tables.ts`; cross-Module money tables in `core.ts`.
 */

import {
	accountRelations,
	approvalRelations,
	auditEventRelations,
	changeSetRelations,
	commandExecutionRelations,
	confirmationRelations,
	fileRelations,
	invitationRelations,
	logRelations,
	moduleEventConsumptionRelations,
	moduleEventDeliveryRelations,
	moduleEventSequenceRelations,
	moduleOutboxEventRelations,
	moduleRelations,
	passkeyRelations,
	sessionRelations,
	standingPermissionRelations,
	standingPermissionUseReservationRelations,
	userRelations,
	webhookDeliveryRelations,
	webhookRelations,
	workflowAttemptRelations,
	workflowRelations,
	workflowStepRelations,
} from "./relations";

import {
	account,
	approval,
	auditEvent,
	changeSet,
	commandExecution,
	confirmation,
	file,
	invitation,
	log,
	module,
	moduleEventConsumption,
	moduleEventDelivery,
	moduleEventSequence,
	moduleOutboxEvent,
	passkey,
	session,
	standingPermission,
	standingPermissionUseReservation,
	user,
	verification,
	webhook,
	webhookDelivery,
	workflow,
	workflowAttempt,
	workflowStep,
} from "./tables";

export const schema = {
	accountRelations,
	approvalRelations,
	auditEventRelations,
	changeSetRelations,
	commandExecutionRelations,
	confirmationRelations,
	fileRelations,
	invitationRelations,
	logRelations,
	moduleEventConsumptionRelations,
	moduleEventDeliveryRelations,
	moduleEventSequenceRelations,
	moduleOutboxEventRelations,
	moduleRelations,
	passkeyRelations,
	sessionRelations,
	standingPermissionRelations,
	standingPermissionUseReservationRelations,
	userRelations,
	webhookDeliveryRelations,
	webhookRelations,
	workflowAttemptRelations,
	workflowRelations,
	workflowStepRelations,
	account,
	approval,
	auditEvent,
	changeSet,
	commandExecution,
	confirmation,
	file,
	invitation,
	log,
	module,
	moduleEventConsumption,
	moduleEventDelivery,
	moduleEventSequence,
	moduleOutboxEvent,
	passkey,
	session,
	standingPermission,
	standingPermissionUseReservation,
	user,
	verification,
	webhook,
	webhookDelivery,
	workflow,
	workflowAttempt,
	workflowStep,
} as const;

export type StoreRuntimeSchema = typeof schema;
