import type { ModuleSchema } from "@86d-app/core/types/schema";

export const ebaySchema = {
	listing: {
		fields: {
			id: { type: "string", required: true },
			localProductId: { type: "string", required: true },
			ebayItemId: { type: "string", required: false },
			title: { type: "string", required: true },
			status: { type: "string", required: true, defaultValue: "draft" },
			listingType: {
				type: "string",
				required: true,
				defaultValue: "fixed-price",
			},
			price: { type: "number", required: true },
			auctionStartPrice: { type: "number", required: false },
			currentBid: { type: "number", required: false },
			bidCount: { type: "number", required: true, defaultValue: 0 },
			quantity: { type: "number", required: true, defaultValue: 1 },
			condition: { type: "string", required: true, defaultValue: "new" },
			categoryId: { type: "string", required: false },
			duration: { type: "string", required: false },
			startTime: { type: "date", required: false },
			endTime: { type: "date", required: false },
			watchers: { type: "number", required: true, defaultValue: 0 },
			views: { type: "number", required: true, defaultValue: 0 },
			lastSyncedAt: { type: "date", required: false },
			error: { type: "string", required: false },
			metadata: { type: "json", required: true, defaultValue: {} },
			createdAt: {
				type: "date",
				required: true,
				defaultValue: () => new Date(),
			},
			updatedAt: {
				type: "date",
				required: true,
				defaultValue: () => new Date(),
				onUpdate: () => new Date(),
			},
		},
	},
	ebayOrder: {
		fields: {
			id: { type: "string", required: true },
			ebayOrderId: { type: "string", required: true },
			status: { type: "string", required: true, defaultValue: "pending" },
			items: { type: "json", required: true, defaultValue: [] },
			subtotal: { type: "number", required: true },
			shippingCost: { type: "number", required: true },
			ebayFee: { type: "number", required: true },
			paymentProcessingFee: { type: "number", required: true },
			total: { type: "number", required: true },
			buyerUsername: { type: "string", required: false },
			buyerName: { type: "string", required: false },
			shippingAddress: { type: "json", required: true, defaultValue: {} },
			trackingNumber: { type: "string", required: false },
			carrier: { type: "string", required: false },
			shipDate: { type: "date", required: false },
			createdAt: {
				type: "date",
				required: true,
				defaultValue: () => new Date(),
			},
			updatedAt: {
				type: "date",
				required: true,
				defaultValue: () => new Date(),
				onUpdate: () => new Date(),
			},
		},
	},
} satisfies ModuleSchema;
